%YAML:1.0
MarkerMap_Configs:
  - ../input/markerMapConfigs/config1.yml
  - ../input/markerMapConfigs/config2.yml
  - ../input/markerMapConfigs/config3.yml
Planes:
  - XZ
  - YZ
  - XY
xOffset: 1000
yOffset: 1000
Denominator: 125
